### ISSUE TITLE
Incorrect autologin token verification when another user is logged in

### ISSUE THREAD

**Issue by twoleds** [remp2020/crm-remp-mailer-module#4]
I think there might be an issue here at: https://github.com/remp2020/crm-remp-mailer-module/blob/13a06bf1251070fc00a1fae77eb330deb7ad005f/src/Presenters/MailSettingsPresenter.php#L98

The `Crm\UsersModule\Auth\AutoLogin\AutoLogin` is used here, but it uses the CRM database and checks the token that comes from the Mailer. However, the Mailer uses its own database, and these databases are not shared. Therefore, the token won't be found in the CRM database, and as a result, this code will never be executed:https://github.com/remp2020/crm-remp-mailer-module/blob/13a06bf1251070fc00a1fae77eb330deb7ad005f/src/Presenters/MailSettingsPresenter.php#L105

I assume that instead of using `AutoLogin`, this function should be called there to make it work correctly:
https://github.com/remp2020/crm-remp-mailer-module/blob/13a06bf1251070fc00a1fae77eb330deb7ad005f/src/Models/Api/Client.php#L49

This function is invoked during user authentication here:
https://github.com/remp2020/crm-remp-mailer-module/blob/13a06bf1251070fc00a1fae77eb330deb7ad005f/src/Models/Authenticator/TokenAuthenticator.php#L69

But only if the user is not logged in:
https://github.com/remp2020/crm-application-module/blob/b79079b765ccf152bc8c251b831e83f6e5b8f7bd/src/Presenters/FrontendPresenter.php#L78

**Comment by rootpd** [comment]
You're right, that is a bug! We're planning to make a major release tomorrow and probably won't be able to include the fix right away, but we'll issue a hotfix as soon as we fix this.

Thanks for the report!

**Comment by rootpd** [comment]
In the end we managed to fix it within the latest release (https://github.com/remp2020/crm-remp-mailer-module/commit/c4cda1b3fd91a538ffc78440697a8b4671cb340b). Thanks for the report!
